version: '3.7'
services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
      target: development
    ports:
      - ${PORT:-3000}:3000
    volumes:
      - ./front/:/app/
      - next_node_modules:/app/node_modules
    environment:
      TZ: ${TZ:-UTC}
      NEXT_PUBLIC_API_URL: http://back:${PORT_API:-1323}
    restart: unless-stopped

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
      target: development
    depends_on:
      - db
    ports:
      - ${PORT_API:-1323}:1323
    volumes:
      - ./back:/go/src/app
      - go_src:/src/
    environment:
      TZ: ${TZ:-UTC}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-prc_hub}
      MYSQL_USER: ${MYSQL_USER:-prc_hub}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
      LOG_LEVEL: ${LOG_LEVEL:-2}
      GZIP_LEVEL: ${GZIP_LEVEL:-6}
      MYSQL_HOST: ${MYSQL_HOST:-db}
      JWT_ISSUER: ${JWT_ISSUER:-prc_hub}
      JWT_SECRET: ${JWT_SECRET}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@prchub.com}
      ADMIN_PASSWD: ${ADMIN_PASSWD:-password}
    restart: unless-stopped

  db:
    image: mysql:8
    volumes:
      - type: bind
        source: "./back/db/init.sql"
        target: "/docker-entrypoint-initdb.d/init.sql"
      - type: bind
        source: "./back/db/my.cnf"
        target: "/etc/mysql/conf.d/my.cnf"
      - ./back/db/log:/var/log/mysql
      - mysql_data:/var/lib/mysql
    environment:
      TZ: ${TZ:-UTC}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-prc_hub}
      MYSQL_USER: ${MYSQL_USER:-prc_hub}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
    ports:
      - 3306
    restart: unless-stopped

  prism:
    image: stoplight/prism:4
    command: 'mock -h 0.0.0.0 /tmp/api.oas3.yml'
    volumes:
      - ./back/api.oas3.yml:/tmp/api.oas3.yml:ro
    ports:
      # Serve the mocked API locally as available on port 8080
      - '${PORT_MOCK:-4010}:4010'

volumes:
  mysql_data:
  next_node_modules:
  go_src: